### ISSUE TITLE
Repositories with package.yaml are not supported

### ISSUE THREAD

**Issue by qrilka** [input-output-hk/nix-tools#36]
Exaple test project could be found at https://github.com/commercialhaskell/stack/tree/master/test/integration/tests/hpack-repo/files
For me (with LTS-12.26 as haskell-nix doesn't suport GHC 8.2.2) it fails with:
```
qrilka@qdesktop ~/ws/h/stack/test/integration/tests/hpack-repo/files/nix $ nix build -f default.nix validity.components.library 
builder for '/nix/store/rqlv2yq2mhkz0r0l6yqxlr1306y0zh4g-validity-0.9.0.0-lib-validity.drv' failed with exit code 1; last 10 log lines:
  unpacking sources
  unpacking source archive /nix/store/pr6dwsl8q19zg2sq5pdkisg2ddpabyii-validity-d128cc3
  source root is validity-d128cc3
  source root reset to validity-d128cc3/validity
  patching sources
  configuring
  Configure flags:
  --prefix=/nix/store/pjp0sj4pfkb5zy7v862dnd2538zfvxp7-validity-0.9.0.0-lib-validity lib:validity --package-db=clear --package-db=/nix/store/c1qn7b1szc52zlbav3nnyjn2fjh87pwn-validity-0.9.0.0-lib-validity-config/package.conf.d --with-ghc=ghc --with-ghc-pkg=ghc-pkg --with-hsc2hs=hsc2hs --with-gcc=cc --with-ld=ld --with-ar=ar --with-strip=strip --enable-executable-stripping --enable-library-stripping --docdir=/nix/store/gjiyg7pbj1blkgmaflmf3lhgjjcy335s-validity-0.9.0.0-lib-validity-doc/share/doc/validity --enable-split-sections 
  Setup: No cabal file found.
  Please create a package description file <pkgname>.cabal
[2 built (1 failed), 0.1 MiB DL]
error: build of '/nix/store/rqlv2yq2mhkz0r0l6yqxlr1306y0zh4g-validity-0.9.0.0-lib-validity.drv' failed
```

I plan to work on fixing this.

**Comment by angerman** [comment]
@qrilka Ohh so that's a case where someone outright went to ditch `.cabal` altogether. 
There is some code in `Cabal2Nix` to set the cabal generator

https://github.com/input-output-hk/nix-tools/blob/f72e330998610a191363f8080bbe056b670ef0c8/lib/Cabal2Nix.hs#L74-L75

I would hope that this was set in the generated validity nix expression?

**Comment by qrilka** [comment]
You're right, there is such a generator in `validity.nix` but somehow it doesn't get properly invoked, and it works not only for dependency (which is make total sense of course), with a project created with `stack new rio-test rio` and with its cabal file removed I get a similar error, I'll try to debug it further later in the day.

**Comment by qrilka** [comment]
@angerman am I right that there is no Nix code using this `cabal-generator` attribute? I see it only defined in `haskell.nix/modules/package.nix` - was it left for later development or I maybe I just miss something here?

**Comment by angerman** [comment]
@qrilka that might be quite right, that we just encoded the info in the nix expression, but the `haskell.nix` runtime does not yet respect it. Thus it might just be a case of needing to implement the necessary `hpack` logic in the component builder in `haskell.nix`.

**Comment by angerman** [comment]
This was fixed in input-output-hk/haskell.nix#82
