### ISSUE TITLE
Problem running tests specified with hspec-discover

### ISSUE THREAD

**Issue by qrilka** [input-output-hk/nix-tools#38]
Hackage contains a lot of packages which rely on `hspec-discover` to get test specs. The problem for `nix-tools` is that they just add `hspec` as a dependency and not `hspec-discover` as a build tool. That leads to tests failing when run with Nix on derivations created by `nix-tools`. I discovered it while working on #36 and simple `stack new rio-test rio` gives a failure like the following:
```
$ nix build -f default.nix rio-test.components.tests
builder for '/nix/store/91zh7sndg1wh8mafxlcpbdcsci019vh5-rio-test-0.1.0.0-test-rio-test-test.drv' failed with exit code 1; last 10 log lines:
  Configure flags:
  --prefix=/nix/store/yd7pp4yymza0ca8vy1j25i1hwdiwfbg8-rio-test-0.1.0.0-test-rio-test-test test:rio-test-test --package-db=clear --package-db=/nix/store/wah22ik1g370j5ysjqs2a29sddky3lzs-rio-test-0.1.0.0-test-rio-test-test-config/package.conf.d --with-ghc=ghc --with-ghc-pkg=ghc-pkg --with-hsc2hs=hsc2hs --with-gcc=cc --with-ld=ld --with-ar=ar --with-strip=strip --enable-executable-stripping --enable-library-stripping --enable-split-sections 
  Configuring test suite 'rio-test-test' for rio-test-0.1.0.0..
  Loaded package environment from /nix/store/wah22ik1g370j5ysjqs2a29sddky3lzs-rio-test-0.1.0.0-test-rio-test-test-config/ghc-environment
  building
  Preprocessing test suite 'rio-test-test' for rio-test-0.1.0.0..
  Building test suite 'rio-test-test' for rio-test-0.1.0.0..
  Loaded package environment from /nix/store/wah22ik1g370j5ysjqs2a29sddky3lzs-rio-test-0.1.0.0-test-rio-test-test-config/ghc-environment
  Loaded package environment from /nix/store/wah22ik1g370j5ysjqs2a29sddky3lzs-rio-test-0.1.0.0-test-rio-test-test-config/ghc-environment
  ghc: could not execute: hspec-discover
[3 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/91zh7sndg1wh8mafxlcpbdcsci019vh5-rio-test-0.1.0.0-test-rio-test-test.drv' failed
```

**Comment by qrilka** [comment]
At the same time both `stack test` and `cabal new-test` seem to work fine in this situation.

**Comment by qrilka** [comment]
It looks like this one is a consequence of the component-based approach in `nix-tools` - in the current `generic-builder.nix` this problem doesn't arise because `hspec` depends on `hspec-discover` and the executable from `hspec-discover` gets automatically available to any package depending on `hspec`. It seems that some option like "propagatedExecutableComponents" could be a solution here but it needs to be enabled per package, so probably would require special handling.

**Comment by angerman** [comment]
I think there's some lengthy thread about a very similar issue between @sol and @hvr somewhere on the cabal issue tracker.

**Comment by ElvishJerricco** [comment]
Yea this bug is a little complicated. cabal-install just assumes that depending on a lib means you need its exe components on the PATH. This was always a bad assumption, so it has become a special case in cabal-install for legacy reasons. The proper fix is to patch any packages using hspec-discover to list that exe in the `build-tool-depends` field in the cabal file, which nix-tools should handle properly. You can probably fix this without editing their cabal file by manually adding build tools in the haskell.nix module system

**Comment by angerman** [comment]
I believe we can close this as *wontfix*. This really ought to be fixed in the package properly and we should not contribute to keping some lingering compat layer. Especially not if it makes our code substantially more complex for no other reason.

**Comment by qrilka** [comment]
I think you're correct and during discussion of this thing in https://github.com/fpco/safe-decimal/pull/1 I've discovered that Cabal also wants this as an explicit dependency but it didn't complain because I had a local install of `hspec-discover` on my $PATH
