### ISSUE TITLE
plan-to-nix does not set necessary flag information

### ISSUE THREAD

**Issue by nomeata** [input-output-hk/nix-tools#42]
I could not get the result of `plan-to-nix`, applied to https://github.com/entropia/tip-toi-reveng, to work without manually adding lines such as
```
      "transformers-compat".flags.two = false;
      "transformers-compat".flags.three = false;
      "transformers-compat".flags.four = false;
      "transformers-compat".flags.five = false;
      "transformers-compat".flags."five-three" = true;
      "time-locale-compat".flags."old-locale" = false;
```

Looking through the `plan.json`, it seems that the correct value of these flags is not noted there, so I am not sure if `plan-to-nix` is to be blamed here, but if not, then the documentation should mention this, I think.

**Comment by angerman** [comment]
There is a slightly improved `plan-to-nix` in input-output-hk/nix-tools#31. But if cabal does not decides that those flags are needed, and subsequently doesn't put them in the `plan.json` file that is indeed an issue. You could always specify them in your `cabal.project` file prior to running `cabal new-configure` and I would hope they end up in the `plan.json`.

Maybe @hvr has some better explanation here.

**Comment by ElvishJerricco** [comment]
I don't understand why you have to manually add these lines. The package expression should be providing defaults.

**Comment by angerman** [comment]
@ElvishJerricco yea, I'm mildly perplexed as well. However I believe @nomeata has mentioned elsewhere that after upgradeing ghc the flags were correct? Am I remembering that correctly @nomeata?

**Comment by nomeata** [comment]
Yes. The first time I ran `plan-to-nix`, I think it was with 8.4.4, and flags for `transformers-compat` and `time-locale-compat` were missing. The second time I ran it with 8.6.3, and they were there. 

Ah, diffing the plans indeed the 8.4.4. plan does not have flags, but it has `type: pre-existing`. Is that a clue?

**Comment by angerman** [comment]
@nomeata yea... pre-existing means that cabal assumes it can pull it from the package-db that ghc shipped with. I wonder if one could restrict this better.

nix-tools tries to rebuild everything as much as it can to produce a consistent buildgraph, and not have to deal with the package-db that ships with ghc.

**Comment by angerman** [comment]
I've just tried this with ghc on `nix-tools`. And I think the underlying issue is that cabal does not know the flags for pre-existing packages. Now I'm not sure where those packages came from, maybe from the global package-db? They are not included in https://downloads.haskell.org/~ghc/8.4.4/docs/html/users_guide/8.4.1-notes.html#included-libraries, nor in https://downloads.haskell.org/~ghc/8.6.3/docs/html/users_guide/8.6.1-notes.html#included-libraries

**Comment by nomeata** [comment]
> Now I'm not sure where those packages came from, maybe from the global package-db? 

Yup, good guess. I am still old-school and get my `ghc` from Debian, including some packages that I like to have available outside of a `cabal` environment.

**Comment by angerman** [comment]
@nomeata does
```
cabal new-configure --package-db=clear --package-db=global
``` 
do the trick?

**Comment by nomeata** [comment]
Probably not (can't test right now), Debian installs packages into the global DB

**Comment by nomeata** [comment]
But not a big deal, I just have to avoid using the system ghc when creating a plan

**Comment by angerman** [comment]
Unless cabal learns some logic, I think this will be hosed if distributions install packages into the global-db. That's quite unfortunate. As far as I can tell we can't do much here though. I'll close it for now.
