### ISSUE TITLE
hackage.nix is very big

### ISSUE THREAD

**Issue by nomeata** [input-output-hk/nix-tools#48]
While packaged 'https://github.com/input-output-hk/hackage.nix/archive/0abc...bf37a47.tar.gz' is reasonably small (24MB), the unpacked directory is half a gig. Not unfeasible, but parsing and hashing that by `nix` is not snappy, so I wonder if there is some low-hanging fruit to improve that – especially if these files are not meant to be manually consumed. Maybe `hackage-to-nix` can have a `--compact` mode that you leave out during development and debugging.

Some (obviously unevaluated) ideas: 
 * use very short auto-generated names in the `hackage/` subdirectory; maybe even only `hackage/1.nix`…
 * leave out the package descriptions (are they used?), and maybe other fields like `maintainer` and `author`
 * Maybe make the `revNum` field optional, and default to `0` upon lookup in `haskell.nix`

Not sure if it is worth it, of course…

**Comment by angerman** [comment]
@nomeata, but haskell.nix doesn’t directly include hackage.nix or stackage.nix. So we are talking about dependencies? One issue with hackage (and the long names) is that I must work on case insensitive filesystems (mac, Windows) and hackage allows packages to only differ in casing \o/

We could debate what forelds are necessary to carry around in the translated cabal expressions.

**Comment by nomeata** [comment]
Edited in places where I confused `haskell.nix` and `hackage.nix` - it's all about the latter :-)

**Comment by nomeata** [comment]
> One issue with hackage (and the long names) is that I must work on case insensitive filesystems (mac, Windows) 

Using very short file names that do not contain the package name here would help with that too, right?

**Comment by angerman** [comment]
> Using very short file names that do not contain the package name here would help with that too, right?
True. Just quite hard to tab-complete in the shell :-) I often find myself with `/path/to/hackage.nix/-containers-0.5` `<tab>`.

Using short unique names here could help though. Not sure how much we'd save in space though, might also depends on filesystem and filesystem parameters.

I wonder if we could teach nix to work with tarballs directly or sqlite databases or something. Anyway, happy for any improvement suggestions you come up with @nomeata.

**Comment by nomeata** [comment]
I wonder what is most valuable to optimize for. Total unpacked size (to avoid hashing writing/reading/hashing too much data)? Total number of files (because file operations are slow, and also nix has to create the store hash from it)? Parsing time?

(Presumably not parsing time, as any particular run will only parse the top-level file and those nix files that are actually used.)

Obvious low-hanging fruit: the description field. Is it actually used anywhere?

Maybe I’ll play around with it. But obviously not very important…

**Comment by nomeata** [comment]
When I said it’s half a gig, then that’s not completely true: It is the size it takes on disk, because of the 100000 many small files. The actual size, `du --apparent-size` is uch less. 

Here are some experiments:

* Original: 269MB unpacked / 25MB packed
* Without description, url, maintainer, synopsis, copyright field: 191MB unpacked / 20MB packed
* Using just 8 chars for the filenames: 168MB unpacked / 24 MB packed
* Using sequential numbers for the filename (thus keeping them in order): 186MB unpacked / 14MB packed

Fun fact, passing `--sort=name` to `tar` seems to help `gzip`, as it puts similar files next to each other.

Hmm, I was hoping for more actually. If gzip can get the data down by 90% means that there is a lot of redundancy in the data; I wonder if there is a way make use of that (if we accept that the output is not primarily for human readable consumption). But maybe this is not the right hill to die on.

**Comment by angerman** [comment]
@nomeata if it's just size, we should proabaly look into teaching nix to read zipped tarballs without extracting them to disk. Or some binary `.nix` format, though I doubt that would help much. I think nix would gain *a lot* by being able to read right out of `.tar.gz` files. Everytime you specify some repository using nix-fetch-tarball or similar you essentially download a tarball, and then extract it. All you really care is downloading the tarball, getting the filemap, reading the `default.nix` and taking it from there.

@shlevy, @domenkozar, @cleverca22 what do you think?

**Comment by nomeata** [comment]
Yes, I had similar thoughts. Note, though, that `.tar.gz` isn’t a particular friendly format for random access, isn’t it?

A binary `.nix` format, especially with string sharing (lots of redundant strings in `.hackage.nix`, especially in field names, but also in the values – package names, versions), could help a lot in terms of size (and speed up parsing along the way). Would be fun to create a binary format that allows lazy parsing, i.e. where only the actually evaluated parts are accessed/parsed.

**Comment by shlevy** [comment]
Hmm I'd like to understand a bit more what specifically we're trying to do here, but in general I think a "compiled"/binary Nix format could make a lot of sense for some use cases.

**Comment by angerman** [comment]
@shlevy as far as I understand @nomeata, the perceived issue is that we are unpacking something that ~25MB into something that about ten times bigger. As someone who consistently runs out of space in his nix-store, I can sympathize with this.

**Comment by Ericson2314** [comment]
Didn't @ElvishJerricco create a trick with the current infra to unpack on demand? I would have thought that would be good here.

**Comment by shlevy** [comment]
Yes, if we have a bunch of small nix expressions in the tarball that don't depend on each other, we can simply unpack each as its own derivation (you can specify a single file to extract from a tarball).

**Comment by nomeata** [comment]
Up early because of a bunch of thoughts here.

* > Would be fun to create a binary format that allows lazy parsing, i.e. where only the actually evaluated parts are accessed/parsed.
   
   No need to wait for `nix` (the binary) to support such a thing; Nix (the language) can just implement it! The string type is just a binary blob, and `builtins.substr` allows random access, so it should be possible and actually quite performant to just define such a binary format, put it into a nix string, and ship it together with an interpreter implemented in Nix.

   (Although, small gotcha: It seems that `nix` implements strings using C strings, so you have to avoid '\0', and `builtins.substr`, because it checks the lengths, is still O(n), unless I am misreading [the C++ source code](https://github.com/NixOS/nix/blob/41ba5135e0a2d9940c4e8cbedff44eb1a47af782/src/libexpr/value.hh#L124).)

* Even without going so far, there are ways of using Nix to encode things more compactly. For example, many values in `hackage.nix` have a common structure, e.g. `{flags = a; package = b; components = c}`. This could be abstracted into a function `f1 a b c`, where `f1` is defined only once.

   In general: Look at all objects literals, and group them by their set of keys. If a key set appears more than once, abstract it out in to a  function. This way, the key names are written only once.

   This can even be iterated: If `f1 a (f2 b c d e) g h` is a common pattern, abstract it out into `f1 a b c d e g h`. (I guess I am defining a form of tree compression algorithm here, using functions as dictionaries into shapes. [Possibly relevant research.](https://link.springer.com/chapter/10.1007/978-3-540-39917-9_25) [More research](http://www-kb.is.s.u-tokyo.ac.jp/~koba/compress/)).

* Surprisingly (at least to the functional programmer), lists in Nix are actually arrays (so `builtins.tail` is O(n), but `builtins.elemAt` is O(1)). So we can easily do string-consing: Put all strings that appear more than once (all the common fields names, but also, in particular, package name, version numbers, buildTypes)  in a long list, `strings = ["ABList", … ]`, and then replace them by `builtins.elemAt n strings`. Or rather, replace them simply by `n` (very short!), and interpret these numbers by a generic function that traverses the AST.

So it would already be quite feasible to write a  `nix-compress` program that takes an arbitrary `.nix` file and, well, compresses it a lot, and the resulting code might, because of the string consing, even take less RAM to evaluate!

**Comment by angerman** [comment]
With #79, hackage.nix is now mostly a json file (motivation: speed), I hope it does help a bit with size as well. We'll have to see. Adding a compression step might be counter productive to the primary concern of performance that has been raised multiple times :-/

**Comment by yorickvP** [comment]
I don't really see a good way to make default.nix/hackage.json smaller, but the individual cabal2nix'd files add a bunch of overhead that could be solved by reading them from a zip file (these are indexed). We'd have to extend nix to do that at evaluation time or use IFD (which will be slow).

**Comment by angerman** [comment]
> I don't really see a good way to make default.nix/hackage.json smaller, but the individual cabal2nix'd files add a bunch of overhead that could be solved by reading them from a zip file (these are indexed). We'd have to extend nix to do that at evaluation time or use IFD (which will be slow).

If would be really nice if Nix supported filepaths like

./file.zip:somefile.ext

**Comment by yorickvP** [comment]
> If would be really nice if Nix supported filepaths like
> 
> ./file.zip:somefile.ext

https://github.com/serokell/scratch/tree/master/nix-plugins/importzip
