### ISSUE TITLE
pkg-config dependency names should be mapped to nix package names

### ISSUE THREAD

**Issue by hamishmack** [input-output-hk/nix-tools#49]
The pkg-config dependency names are not mapped in cabal-to-nix.  For instance `haskell-gi-base` in `hackage.nix` has `pkgconfig = [ (pkgconfPkgs.gobject-2.0) (pkgconfPkgs.glib-2.0) ];`.

I think Cabal2Nix does the mapping with [this](https://github.com/NixOS/cabal2nix/blob/11c68fdc79461fb74fa1dfe2217c3709168ad752/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs#L16)

**Comment by angerman** [comment]
I think we are just missing the relevant mapping in here: 

https://github.com/input-output-hk/haskell.nix/blob/master/lib/pkgconf-nixpkgs-map.nix

all the `nix-tools` Should do a faithfull translation of the source representation into nix. And the nix runtime (haskell.nix) is then responsible for the right mappings. We don’t want to hardcode nixpkgs logic into nix-tools unless we absolutely have to.

**Comment by hamishmack** [comment]
We might need to replace `.` with `_` or something though.

**Comment by angerman** [comment]
There is some quoting logic in nix-tools, I assume this should be applied here. Such that it reads `pkgconfPkgs.”gobject-2.0”`. That might be missing from pkgconfPkgs

**Comment by angerman** [comment]
This was fixed in 914a77e.
