### ISSUE TITLE
Tool to extract external sources in stack project

### ISSUE THREAD

**Issue by purefn** [input-output-hk/nix-tools#70]
One problem with using `stackProject` in `haskell.nix` is external sources, i.e. dependencies not in stackage or hackage, with source on GitHub. You can provide a cache set to `stackProject`, but that's very manual and duplicates the information in the stack files. 

To avoid this, we could build an exe that uses the existing code from `stack-to-nix` to produce nix expressions containing the data needed for calling `fetchgit` and build the cache set to pass to `stackProject` - or `stackProject` could transparently build the cache itself.

**Comment by cdepillabout** [comment]
I think this was added in #72 and can probably be closed.
