### ISSUE TITLE
Support new format for Stackage snapshots

### ISSUE THREAD

**Issue by eamsden** [input-output-hk/nix-tools#77]
The current format for stackage snapshots is being discontinued: https://www.stackage.org/blog/2020/02/discontinuing-legacy-snapshots

If nix-tools/haskell.nix is to support Stackage snapshots going forward, it will need to parse the new format using Pantry. A beginning pointer is provided at: https://www.stackage.org/blog/2019/07/new-snapshot-format

**Comment by angerman** [comment]
This is now in nix-tools, just needs the hackage/stackage bumps fixed.
